package com.can.appstore.message.db.dao;

import com.can.appstore.message.db.entity.MessageInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageInfoDaoConfig;

    private final MessageInfoDao messageInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageInfoDaoConfig = daoConfigMap.get(MessageInfoDao.class).clone();
        messageInfoDaoConfig.initIdentityScope(type);

        messageInfoDao = new MessageInfoDao(messageInfoDaoConfig, this);

        registerDao(MessageInfo.class, messageInfoDao);
    }
    
    public void clear() {
        messageInfoDaoConfig.getIdentityScope().clear();
    }

    public MessageInfoDao getMessageInfoDao() {
        return messageInfoDao;
    }

}
