package cn.can.downloadlib;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "download".
 */
@Entity(nameInDb = "download")
public class DownloadDBEntity {

    @Id
    private String downloadId;
    private Long totalSize;
    private Long downloadedSize;
    private String url;
    private String saveDirPath;
    private String fileName;
    private Integer downloadStatus;
    private String icon;

    @Generated(hash = 1143139915)
    public DownloadDBEntity() {
    }

    public DownloadDBEntity(String downloadId) {
        this.downloadId = downloadId;
    }

    @Generated(hash = 500647050)
    public DownloadDBEntity(String downloadId, Long totalSize, Long downloadedSize, String url, String saveDirPath, String fileName, Integer downloadStatus, String icon) {
        this.downloadId = downloadId;
        this.totalSize = totalSize;
        this.downloadedSize = downloadedSize;
        this.url = url;
        this.saveDirPath = saveDirPath;
        this.fileName = fileName;
        this.downloadStatus = downloadStatus;
        this.icon = icon;
    }

    public String getDownloadId() {
        return downloadId;
    }

    public void setDownloadId(String downloadId) {
        this.downloadId = downloadId;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    public Long getDownloadedSize() {
        return downloadedSize;
    }

    public void setDownloadedSize(Long downloadedSize) {
        this.downloadedSize = downloadedSize;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getSaveDirPath() {
        return saveDirPath;
    }

    public void setSaveDirPath(String saveDirPath) {
        this.saveDirPath = saveDirPath;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Integer getDownloadStatus() {
        return downloadStatus;
    }

    public void setDownloadStatus(Integer downloadStatus) {
        this.downloadStatus = downloadStatus;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}
